// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2024-present Datadog, Inc.

package poetry

import (
	"os"
	"path/filepath"
	"testing"
)

// Mirrors tests/package_managers/test_poetry_lock.py.

const pypiLockEntry = `# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = []
`

const privateSourceLockEntry = `# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "internal-lib"
version = "1.0.0"
description = "An internal library."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "legacy"
url = "https://private.company.com/simple/"
reference = "private"
`

const localSourceLockEntry = `# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "my-lib"
version = "0.1.0"
description = "A local library."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "directory"
url = "/absolute/path/to/my-lib"
`

const relativeLocalSourceLockEntry = `# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "sibling-lib"
version = "0.1.0"
description = "A local library referenced by a relative path."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "directory"
url = "../sibling-lib"
`

func TestParsePoetryLockFile_PyPIPackage(t *testing.T) {
	lockPath := filepath.Join(t.TempDir(), "poetry.lock")
	if err := os.WriteFile(lockPath, []byte(pypiLockEntry), 0o644); err != nil {
		t.Fatalf("failed to write test lock file: %v", err)
	}

	sourceMap, err := parsePoetryLockFile(lockPath)
	if err != nil {
		t.Fatalf("parsePoetryLockFile() returned unexpected error: %v", err)
	}

	key := poetryPackageKey{name: "requests", version: "2.31.0"}
	want := "https://pypi.org/project/requests/2.31.0/"
	if got := sourceMap[key]; got != want {
		t.Fatalf("sourceMap[%+v] = %q, want %q", key, got, want)
	}
}

func TestParsePoetryLockFile_PrivateSource(t *testing.T) {
	lockPath := filepath.Join(t.TempDir(), "poetry.lock")
	if err := os.WriteFile(lockPath, []byte(privateSourceLockEntry), 0o644); err != nil {
		t.Fatalf("failed to write test lock file: %v", err)
	}

	sourceMap, err := parsePoetryLockFile(lockPath)
	if err != nil {
		t.Fatalf("parsePoetryLockFile() returned unexpected error: %v", err)
	}

	key := poetryPackageKey{name: "internal-lib", version: "1.0.0"}
	want := "https://private.company.com/simple/"
	if got := sourceMap[key]; got != want {
		t.Fatalf("sourceMap[%+v] = %q, want %q", key, got, want)
	}
}

func TestParsePoetryLockFile_LocalSource(t *testing.T) {
	lockPath := filepath.Join(t.TempDir(), "poetry.lock")
	if err := os.WriteFile(lockPath, []byte(localSourceLockEntry), 0o644); err != nil {
		t.Fatalf("failed to write test lock file: %v", err)
	}

	sourceMap, err := parsePoetryLockFile(lockPath)
	if err != nil {
		t.Fatalf("parsePoetryLockFile() returned unexpected error: %v", err)
	}

	key := poetryPackageKey{name: "my-lib", version: "0.1.0"}
	want := "/absolute/path/to/my-lib"
	if got := sourceMap[key]; got != want {
		t.Fatalf("sourceMap[%+v] = %q, want %q", key, got, want)
	}
}

func TestParsePoetryLockFile_RelativeLocalSource(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "main-pkg")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatalf("failed to create project dir: %v", err)
	}
	lockPath := filepath.Join(projectDir, "poetry.lock")
	if err := os.WriteFile(lockPath, []byte(relativeLocalSourceLockEntry), 0o644); err != nil {
		t.Fatalf("failed to write test lock file: %v", err)
	}

	sourceMap, err := parsePoetryLockFile(lockPath)
	if err != nil {
		t.Fatalf("parsePoetryLockFile() returned unexpected error: %v", err)
	}

	key := poetryPackageKey{name: "sibling-lib", version: "0.1.0"}
	want, err := filepath.Abs(filepath.Join(projectDir, "..", "sibling-lib"))
	if err != nil {
		t.Fatalf("filepath.Abs() failed: %v", err)
	}
	if got := sourceMap[key]; got != want {
		t.Fatalf("sourceMap[%+v] = %q, want %q", key, got, want)
	}
}

func TestParsePoetryLockFile_MissingFile(t *testing.T) {
	if _, err := parsePoetryLockFile(filepath.Join(t.TempDir(), "poetry.lock")); err == nil {
		t.Fatal("parsePoetryLockFile() = nil error, want error for a missing file")
	}
}

func TestResolvePoetryProjectDir_AllFlagForms(t *testing.T) {
	tests := []struct {
		name    string
		command []string
	}{
		{name: "space-separated long form", command: []string{"update", "--directory", "/tmp/proj"}},
		{name: "equals long form", command: []string{"update", "--directory=/tmp/proj"}},
		{name: "space-separated short form", command: []string{"update", "-C", "/tmp/proj"}},
		{name: "attached short form", command: []string{"update", "-C/tmp/proj"}},
		{name: "equals short form", command: []string{"update", "-C=/tmp/proj"}},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, err := resolvePoetryProjectDir(tc.command)
			if err != nil {
				t.Fatalf("resolvePoetryProjectDir(%v) returned unexpected error: %v", tc.command, err)
			}
			if want := "/tmp/proj"; got != want {
				t.Fatalf("resolvePoetryProjectDir(%v) = %q, want %q", tc.command, got, want)
			}
		})
	}
}

func TestResolvePoetryProjectDir_NoFlagFallsBackToCwd(t *testing.T) {
	want, err := os.Getwd()
	if err != nil {
		t.Fatalf("os.Getwd() failed: %v", err)
	}

	got, err := resolvePoetryProjectDir([]string{"update"})
	if err != nil {
		t.Fatalf("resolvePoetryProjectDir() returned unexpected error: %v", err)
	}
	if got != want {
		t.Fatalf("resolvePoetryProjectDir() = %q, want %q", got, want)
	}
}

func TestStripPoetryDirectoryFlag_AllFlagForms(t *testing.T) {
	tests := []struct {
		name    string
		command []string
	}{
		{name: "space-separated long form", command: []string{"update", "--directory", "/tmp/proj", "--lock"}},
		{name: "equals long form", command: []string{"update", "--directory=/tmp/proj", "--lock"}},
		{name: "space-separated short form", command: []string{"update", "-C", "/tmp/proj", "--lock"}},
		{name: "attached short form", command: []string{"update", "-C/tmp/proj", "--lock"}},
		{name: "equals short form", command: []string{"update", "-C=/tmp/proj", "--lock"}},
	}

	want := []string{"update", "--lock"}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := stripPoetryDirectoryFlag(tc.command)
			if len(got) != len(want) {
				t.Fatalf("stripPoetryDirectoryFlag(%v) = %v, want %v", tc.command, got, want)
			}
			for i := range got {
				if got[i] != want[i] {
					t.Fatalf("stripPoetryDirectoryFlag(%v) = %v, want %v", tc.command, got, want)
				}
			}
		})
	}
}

func TestStripPoetryDirectoryFlag_NoFlagIsUnchanged(t *testing.T) {
	command := []string{"update", "--lock"}
	got := stripPoetryDirectoryFlag(command)
	if len(got) != len(command) {
		t.Fatalf("stripPoetryDirectoryFlag(%v) = %v, want unchanged %v", command, got, command)
	}
	for i := range got {
		if got[i] != command[i] {
			t.Fatalf("stripPoetryDirectoryFlag(%v) = %v, want unchanged %v", command, got, command)
		}
	}
}
