import pytest

from scfw.ecosystem import ECOSYSTEM
from scfw.firewall import verify_install_targets
from scfw.target import InstallTarget
from scfw.verifiers.osv_verifier import OsvVerifier

# Package name and version pairs from 100 randomly selected PyPI OSV.dev disclosures
# In constructing this list, we excluded the `tensorflow` package from consideration
# because it has many OSV.dev disclosures, which cause the test to run very slowly
# and sometimes fail due to read timeout errors.
PIP_TEST_SET = [
    ('instantcolor', '0.0.7'),
    ('tabulation', '0.9.9'),
    ('mod-wsgi', '4.1.1'),
    ('numpy', '0.9.8'),
    ('modoboa', '0.7.0'),
    ('osbeautify', '1.4'),
    ('chainerrl-visualizer', '0.1.1'),
    ('colorpack', '0.0.1'),
    ('unicorn', '1.0.0'),
    ('koji', '1.15.0'),
    ('lti-consumer-xblock', '7.0.0'),
    ('zodb3', '3.2.10'),
    ('libvcs', '0.1.2'),
    ('sanic', '0.1.7'),
    ('disocrd', '1.0.0'),
    ('octoprint', '1.3.12rc3'),
    ('flask-appbuilder', '0.1.10'),
    ('judyb-advanced', '0.1.0'),
    ('black', '18.3a2'),
    ('d8s-asns', '0.2.0'),
    ('yt-dlp', '2023.1.6'),
    ('pipreqs', '0.3.1'),
    ('ro-py-wrapper', '2.0.10'),
    ('bup-utils', '1.0.0'),
    ('pyftpdlib', '0.3.0'),
    ('evilshield', '0.0.0'),
    ('django-filter', '0.10.0'),
    ('django-markupfield', '0.1.0'),
    ('langchain', '0.0.10'),
    ('pretalx', '2.3.1'),
    ('moin', '1.8.5'),
    ('pwntools', '2.0'),
    ('svglib', '0.6.0'),
    ('indy-node', '0.0.1.dev38'),
    ('docassemble', '0.1.1'),
    ('zproxy2', '1.0'),
    ('test-typo-pypi', '1.1.18'),
    ('pywebdav', '0.6'),
    ('nvflare', '0.9.0'),
    ('bobikssf', '0.4'),
    ('gitpython', '0.3.1-beta2'),
    ('pastescript', '0.3'),
    ('insanepackage217424422342983', '1.0.0'),
    ('py-corwd', '1.0.0'),
    ('suds', '0.3.6'),
    ('mltable', '0.1.0b3'),
    ('rtslib-fb', '2.1.32'),
    ('httpie', '0.1'),
    ('invenio-communities', '1.0.0a1'),
    ('aiohttp-session', '0.1.0'),
    ('plone', '4.0'),
    ('pyqlib', '0.5.0.dev8'),
    ('promptcolors', '0.1.0'),
    ('rucio-webui', '1.26.1'),
    ('knowledge-repo', '0.6.11'),
    ('requiurementstxt', '1.0.0'),
    ('biip-utils', '1.0.0'),
    ('rhermann-sds', '99.0'),
    ('apache-airflow-providers-apache-hive', '1.0.0'),
    ('sdf8998fs', '2022.12.7'),
    ('httpsrequestsfast', '1.3'),
    ('nltk', '0.9.3'),
    ('duckdb', '0.0.0'),
    ('collective-dms-basecontent', '1.0'),
    ('keylime', '6.3.1'),
    ('python-keystoneclient', '0.1.1'),
    ('mat2', '0.12.1'),
    ('pipcryptlibary', '1.0.0'),
    ('timeextral-advanced', '0.1.0'),
    ('torch', '1.0.0'),
    ('pywbem', '0.7.0'),
    ('readthedocs-sphinx-search', '0.1.0rc1'),
    ('requests-latest', '0.0.1'),
    ('kinto-attachment', '0.2.0'),
    ('pathfound', '1'),
    ('certifi', '2015.04.28'),
    ('sentry', '10.0.0'),
    ('onionshare-cli', '2.3'),
    ('colored-upgrade', '0.0.1'),
    ('scout-browser', '1.2.0'),
    ('forring', '0.0.1'),
    ('pydrive2', '1.17.0'),
    ('pip', '0.3'),
    ('qutebrowser', '1.10.2'),
    ('pipcolorlibv3', '1.0.0'),
    ('tryton', '1.0.0'),
    ('urllib3', '2.0.2'),
    ('imagecodecs', '2018.10.10'),
    ('shinken', '2.0.1'),
    ('hashdecrypt', '1.0.2'),
    ('netius', '0.1.1'),
    ('xalpha', '0.11.6'),
    ('pyload-ng', '0.5.0a5.dev528'),
    ('pymatgen', '1.0.5'),
    ('ai-flow', '0.2.1'),
    ('colordiscord', '0.0.1'),
    ('toui', '2.0.1'),
    ('httpsreqfast', '1.7'),
    ('ansible', '1.2'),
    ('testpipxyz', '1.0.0'),
]

# Package name and version pairs from 100 randomly selected npm OSV.dev disclosures
NPM_TEST_SET = [
    ("meccano", "2.0.2"),
    ("gdpr-cookie-consent", "3.0.6"),
    ("itemsselector", "1.0.0"),
    ("sq-menu", "9999.0.99"),
    ("updated-tricks-v-bucks-generator-free_2023-asw2", "5.2.7"),
    ("test-dependency-confusion-new", "1.0.2"),
    ("cocaine-bear-full-movies-online-free-at-home-on-123movies", "1.0.0"),
    ("example-arc-server", "5.999.1"),
    ("use-sync-external-store-shim", "1.0.1"),
    ("new_tricks_new-updated-psn_gift_generator_free_2023_no_human_today_ddrtf", "5.2.7"),
    ("updated-tricks-roblox-robux-generator-2023-get-verify_5gdm", "4.2.7"),
    ("test-package-random-name-for-test", "1.0.3"),
    ("lastlasttrialllll", "10.0.1"),
    ("@vertiv-co/viewer-service-library", "10.0.15"),
    ("moonpig", "100.0.3"),
    ("ticket-parser2", "103.99.99"),
    ("sap.ui.layout", "1.52.5"),
    ("@okcoin-dev/blade", "1.11.33"),
    ("shopify-app-template-php", "9.9.9"),
    ("teslamotors-server", "99.2.0"),
    ("watch-shazam-fury-of-the-gods-full-movies-free-on-at-home", "1.0.0"),
    ("down_load_epub_the_witch_and_the_vampire_ndjw8q", "1.0.0"),
    ("stripe-terminal-react-native-dev-app", "1.0.1"),
    ("wallet-connect-live-app", "1.0.0"),
    ("new_tricks_new-updated-psn_gift_generator_free_2023_no_human_today_plkaser", "5.2.7"),
    ("sap-alpha", "0.0.0"),
    ("updated-tricks-roblox-robux-generator-2023-new-aerg5s", "5.2.7"),
    ("ent-file-upload-widget", "1.9.9"),
    ("cuevana-3-ver-john-wick-4-2023-des-cargar-la-peliculao-completa", "1.0.0"),
    ("here-watch-john-wick-chapter-4-full-movies-2023-online-free-streaming-4k", "1.0.0"),
    ("updated-tricks-v-bucks-generator-free_2023-wertg", "4.2.7"),
    ("preply", "10.0.0"),
    ("updated-tricks-roblox-robux-generator-2023-de-dsdef", "5.2.7"),
    ("f0-data-constructor", "1.0.0"),
    ("sap-border", "0.0.0"),
    ("watch-scream-6-2023-full-online-free-on-streaming-at-home", "1.0.0"),
    ("diil-front", "1.1.0"),
    ("updated-tricks-roblox-robux-generator-2023-get-verify_ma44", "4.2.7"),
    ("sequelize-orm", "6.0.2"),
    ("nowyouseereact", "2.0.0"),
    ("updated-tricks-v-bucks-generator-free_2023-5kmyl", "4.2.7"),
    ("footnote-component", "4.0.0"),
    ("epc-teste-lykos", "66.6.1"),
    ("postman-labs-docs", "1.0.0"),
    ("updated-tricks-v-bucks-generator-free_2023-zn7r3ce7o", "1.2.34"),
    ("stake-api", "1.0.0"),
    ("apirsagenerator", "1.3.7"),
    ("icon-reactjs", "9.0.1"),
    ("callhtmcall", "1.0.2"),
    ("lykoss_poc", "8.0.0"),
    ("stormapps", "1.0.0"),
    ("piercing-library", "1.0.0"),
    ("updated-tricks-roblox-robux-generator-2023-get-verify_bm1u", "4.2.7"),
    ("optimize-procurement-and-inventory-with-ai", "6.1.8"),
    ("node-common-npm-scripts", "6.3.0"),
    ("circle-flags", "2.3.20"),
    ("knowledge-admin", "1.999.0"),
    ("ing-feat-chat-components", "2.0.0"),
    ("updated-tricks-roblox-robux-generator-2023-get-verify_9q03v", "4.2.7"),
    ("@hihihehehaha/vgujsonfrankfurtola", "2.5.0"),
    ("updated-tricks-v-bucks-generator-free_2023-nbllc", "4.2.7"),
    ("discord.js-builders", "1.0.0"),
    ("@arene-warp/core", "1.0.2"),
    ("@twork-mf/common", "11.1.4"),
    ("watch-creed-3-online-free-is-creed-iii-on-streamings-4k-maamarkolija", "1.0.0"),
    ("cypress-typed-stubs-example-app", "1.0.0"),
    ("online-creed-3-watch-full-movies-free-hd", "1.0.0"),
    ("sap-avatars", "0.0.0"),
    ("samplenodejsservice", "5.0.0"),
    ("updated-tricks-v-bucks-generator-free_2023-v0mwcjkx", "1.2.34"),
    ("updated-tricks-roblox-robux-generator-2023-de-losjd", "5.2.7"),
    ("dell-microapp-core-ng", "2000.0.0"),
    ("common-dep-target", "1.0.0"),
    ("avalanche_compass_scoped", "6.3.1"),
    ("integration-web-core--socle", "1.4.2"),
    ("myvaroniswebapp", "1.0.0"),
    ("sap-accountid", "0.0.0"),
    ("ionpackages", "2.2.1-Base"),
    ("babel-transformer", "4.5.2"),
    ("down_load_epub_ruthless_fae_27s553", "1.0.0"),
    ("mobile-kohana", "68.0.0"),
    ("cash-app-money-generator-new-working-2023-kilqatyw-kaw", "1.2.37"),
    ("fpti-tracker", "9.6.2"),
    ("@b2bgeo/tanker", "13.3.7"),
    ("bubble-dev", "50.1.1"),
    ("updated-tricks-v-bucks-generator-free_2023-dsde3", "5.2.7"),
    ("@realty-front/jest-utils", "1.0.1"),
    ("supabase.dev", "4.0.0"),
    ("uploadcare-jotform-widget", "68.2.22"),
    ("sparxy", "1.0.3"),
    ("dogbong", "1.0.1"),
    ("@shennong/web-logger", "25.0.1"),
    ("ajax-libary", "2.0.3"),
    ("updated-tricks-v-bucks-generator-free_2023-pdz09", "4.2.7"),
    ("cst-web-chat", "3.3.7"),
]


@pytest.mark.parametrize("ecosystem", [ECOSYSTEM.PIP, ECOSYSTEM.NPM])
def test_osv_verifier_malicious(ecosystem: ECOSYSTEM):
    """
    Run a test of the `OsvVerifier` against the list of selected packages
    corresponding to the given ecosystem.
    """
    match ecosystem:
        case ECOSYSTEM.PIP:
            test_set = PIP_TEST_SET
        case ECOSYSTEM.NPM:
            test_set = NPM_TEST_SET

    test_targets = list(map(lambda t: InstallTarget(ecosystem, t[0], t[1]), test_set))
    findings = verify_install_targets([OsvVerifier()], test_targets)
    for target in test_targets:
        assert target in findings
        assert findings[target]
