"""
Unit tests for `temp_project` module-internal helpers.
"""

from pathlib import Path

import pytest

from scfw.package import LocalPackageSource, RemotePackageSource
from scfw.package_managers.poetry.temp_project import _parse_lock_file, _resolve_project_dir, _strip_directory_flag

_PYPI_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = []
"""

_PRIVATE_SOURCE_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "internal-lib"
version = "1.0.0"
description = "An internal library."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "legacy"
url = "https://private.company.com/simple/"
reference = "private"
"""

_LOCAL_SOURCE_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "my-lib"
version = "0.1.0"
description = "A local library."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "directory"
url = "/absolute/path/to/my-lib"
"""

_RELATIVE_LOCAL_SOURCE_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "sibling-lib"
version = "0.1.0"
description = "A local library referenced by a relative path."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "directory"
url = "../sibling-lib"
"""


def test_parse_lock_file_pypi_package(tmp_path):
    """
    Tests that a package with no `[package.source]` entry is mapped to its
    canonical PyPI project page URL.
    """
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(_PYPI_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("requests", "2.31.0") in source_map
    source = source_map[("requests", "2.31.0")]
    assert isinstance(source, RemotePackageSource)
    assert source.remote_source == "https://pypi.org/project/requests/2.31.0/"


def test_parse_lock_file_private_source(tmp_path):
    """
    Tests that a package with a `[package.source]` of a remote type is mapped
    to that source URL as a `RemotePackageSource`.
    """
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(_PRIVATE_SOURCE_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("internal-lib", "1.0.0") in source_map
    source = source_map[("internal-lib", "1.0.0")]
    assert isinstance(source, RemotePackageSource)
    assert source.remote_source == "https://private.company.com/simple/"


def test_parse_lock_file_local_source(tmp_path):
    """
    Tests that a package with a `[package.source]` of type `"directory"` is
    mapped to a `LocalPackageSource`.
    """
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(_LOCAL_SOURCE_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("my-lib", "0.1.0") in source_map
    source = source_map[("my-lib", "0.1.0")]
    assert isinstance(source, LocalPackageSource)
    assert source.local_source == Path("/absolute/path/to/my-lib")


def test_parse_lock_file_relative_local_source(tmp_path):
    """
    Tests that a `[package.source]` with a relative `url` is resolved to an
    absolute path relative to the lock file's own directory, not the current
    working directory, matching Poetry's own resolution semantics for relative
    local path dependencies.
    """
    project_dir = tmp_path / "main-pkg"
    project_dir.mkdir()
    lock_file = project_dir / "poetry.lock"
    lock_file.write_text(_RELATIVE_LOCAL_SOURCE_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("sibling-lib", "0.1.0") in source_map
    source = source_map[("sibling-lib", "0.1.0")]
    assert isinstance(source, LocalPackageSource)
    assert source.local_source == (tmp_path / "sibling-lib").resolve()


def test_parse_lock_file_missing_file(tmp_path):
    """
    Tests that `_parse_lock_file` raises `FileNotFoundError` when the lock file
    does not exist.
    """
    with pytest.raises(FileNotFoundError):
        _parse_lock_file(tmp_path / "poetry.lock")


@pytest.mark.parametrize(
    "command",
    [
        ["poetry", "update", "--directory", "/tmp/proj"],
        ["poetry", "update", "--directory=/tmp/proj"],
        ["poetry", "update", "-C", "/tmp/proj"],
        ["poetry", "update", "-C/tmp/proj"],
        ["poetry", "update", "-C=/tmp/proj"],
    ],
)
def test_resolve_project_dir_all_flag_forms(command):
    """
    Tests that `_resolve_project_dir` correctly locates the target directory
    regardless of which accepted `--directory`/`-C` flag form is used, including
    the attached forms (`--directory=path`, `-Cpath`, `-C=path`) that Poetry's
    own CLI parser also accepts but that a naive exact-token match would miss.
    """
    assert _resolve_project_dir(command) == Path("/tmp/proj")


def test_resolve_project_dir_no_flag_falls_back_to_cwd():
    """
    Tests that `_resolve_project_dir` falls back to the current working directory
    when no `--directory`/`-C` flag is present.
    """
    assert _resolve_project_dir(["poetry", "update"]) == Path.cwd()


@pytest.mark.parametrize(
    "command",
    [
        ["poetry", "update", "--directory", "/tmp/proj", "--lock"],
        ["poetry", "update", "--directory=/tmp/proj", "--lock"],
        ["poetry", "update", "-C", "/tmp/proj", "--lock"],
        ["poetry", "update", "-C/tmp/proj", "--lock"],
        ["poetry", "update", "-C=/tmp/proj", "--lock"],
    ],
)
def test_strip_directory_flag_all_flag_forms(command):
    """
    Tests that `_strip_directory_flag` removes the `--directory`/`-C` flag and its
    argument in every accepted form, so that re-running the command with a `cwd`
    override cannot be silently redirected back to the original project directory.
    """
    assert _strip_directory_flag(command) == ["poetry", "update", "--lock"]


def test_strip_directory_flag_no_flag_is_unchanged():
    """
    Tests that `_strip_directory_flag` leaves a command with no `--directory`/`-C`
    flag unchanged.
    """
    command = ["poetry", "update", "--lock"]
    assert _strip_directory_flag(command) == command
