"""
Unit tests for `_parse_lock_file`.
"""

from pathlib import Path

import pytest

from scfw.package import LocalPackageSource, RemotePackageSource
from scfw.package_managers.poetry import _parse_lock_file

_PYPI_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = []
"""

_PRIVATE_SOURCE_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "internal-lib"
version = "1.0.0"
description = "An internal library."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "legacy"
url = "https://private.company.com/simple/"
reference = "private"
"""

_LOCAL_SOURCE_ENTRY = """\
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.

[[package]]
name = "my-lib"
version = "0.1.0"
description = "A local library."
optional = false
python-versions = ">=3.10"
files = []

[package.source]
type = "directory"
url = "/absolute/path/to/my-lib"
"""


def test_parse_lock_file_pypi_package(tmp_path):
    """
    Tests that a package with no `[package.source]` entry is mapped to its
    canonical PyPI project page URL.
    """
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(_PYPI_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("requests", "2.31.0") in source_map
    source = source_map[("requests", "2.31.0")]
    assert isinstance(source, RemotePackageSource)
    assert source.remote_source == "https://pypi.org/project/requests/2.31.0/"


def test_parse_lock_file_private_source(tmp_path):
    """
    Tests that a package with a `[package.source]` of a remote type is mapped
    to that source URL as a `RemotePackageSource`.
    """
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(_PRIVATE_SOURCE_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("internal-lib", "1.0.0") in source_map
    source = source_map[("internal-lib", "1.0.0")]
    assert isinstance(source, RemotePackageSource)
    assert source.remote_source == "https://private.company.com/simple/"


def test_parse_lock_file_local_source(tmp_path):
    """
    Tests that a package with a `[package.source]` of type `"directory"` is
    mapped to a `LocalPackageSource`.
    """
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(_LOCAL_SOURCE_ENTRY)

    source_map = _parse_lock_file(lock_file)

    assert ("my-lib", "0.1.0") in source_map
    source = source_map[("my-lib", "0.1.0")]
    assert isinstance(source, LocalPackageSource)
    assert source.local_source == Path("/absolute/path/to/my-lib")


def test_parse_lock_file_missing_file(tmp_path):
    """
    Tests that `_parse_lock_file` raises `FileNotFoundError` when the lock file
    does not exist.
    """
    with pytest.raises(FileNotFoundError):
        _parse_lock_file(tmp_path / "poetry.lock")
