# Policy for: .github/workflows/release.yml
issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:DataDog@230443989/scfw@1322025239:ref:refs/tags/v[0-9]+\.[0-9]+\.[0-9]+

claim_pattern:
  event_name: push
  job_workflow_ref: DataDog/scfw/\.github/workflows/release\.yml@refs/tags/v[0-9]+\.[0-9]+\.[0-9]+
  ref: refs/tags/v[0-9]+\.[0-9]+\.[0-9]+
  repository: DataDog/scfw

permissions:
  contents: write
