name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall CLI
        run: make test-cli

  pip-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pip-version: ["22.2", "22.3", "23.0", "23.1", "23.2", "23.3", "24.0", "24.1", "24.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install pip==${{ matrix.pip-version }}
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall pip integration
        run: make test-pip

  npm-integration-7x:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        npm-version: ["7.0", "7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "7.7", "7.8", "7.9", "7.10", "7.11", "7.12", "7.13", "7.14", "7.15", "7.16", "7.17", "7.18", "7.19", "7.20", "7.21", "7.22", "7.23", "7.24"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Install Node.js v15.0.0
        uses: actions/setup-node@v4
        with:
          node-version: "15.0.0"
      - name: Test firewall npm integration
        run: |
          npm install -g agentkeepalive
          npm install -g npm@${{ matrix.npm-version }}
          echo "npm version:" $(npm -v)
          make test-npm

  npm-integration-8x:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        npm-version: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5", "8.6", "8.7", "8.8", "8.9", "8.10", "8.11", "8.12", "8.13", "8.14", "8.15", "8.16"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Install Node.js v16.0.0
        uses: actions/setup-node@v4
        with:
          node-version: "16.0.0"
      - name: Test firewall npm integration
        run: |
          npm install -g npm@${{ matrix.npm-version }}
          echo "npm version:" $(npm -v)
          make test-npm

  npm-integration-9x:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        npm-version: ["9.0", "9.1", "9.2", "9.3", "9.4", "9.5", "9.6", "9.7", "9.8", "9.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Install Node.js v19.0.0
        uses: actions/setup-node@v4
        with:
          node-version: "19.0.0"
      - name: Test firewall npm integration
        run: |
          npm install -g npm@${{ matrix.npm-version }}
          echo "npm version:" $(npm -v)
          make test-npm

  npm-integration-10x:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        npm-version: ["10.0", "10.1", "10.2", "10.3", "10.4", "10.5", "10.6", "10.7", "10.8"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Install Node.js v22.0.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.0.0"
      - name: Test firewall npm integration
        run: |
          npm install -g npm@${{ matrix.npm-version }}
          echo "npm version:" $(npm -v)
          make test-npm

  verifiers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall installation target verifiers
        run: make test-verifiers
