name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall CLI
        run: pytest tests/test_cli.py

  pip-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pip-version: ["22.2", "22.3", "23.0", "23.1", "23.2", "23.3", "24.0", "24.1", "24.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install pip==${{ matrix.pip-version }}
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall pip v${{ matrix.pip-version }} integration
        run: |
          pytest tests/commands/test_pip.py tests/commands/test_pip_command.py
