name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall CLI
        run: make test-cli

  pip-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pip-version: ["22.2", "22.3", "23.0", "23.1", "23.2", "23.3", "24.0", "24.1", "24.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install pip==${{ matrix.pip-version }}
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall pip integration
        run: make test-pip

  npm-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x", "15.x", "16.x", "17.x", "18.x", "19.x", "20.x", "21.x", "22.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Install Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test firewall npm integration
        run: make test-npm

  verifiers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install supply-chain firewall
        run: pip install .
      - name: Test firewall installation target verifiers
        run: make test-verifiers
